OWNERS_ALIASES

Adding @tomassedovic, @iamemilio and @trown who are taking a more active role in this repository.

Add reviewers

---

pkg/cloud/openstack/machine/actuator.go

If the `cluster` variable passed to the actuator's `Create` function
is `nil`, fall back to reading the `clusterName` from the `machine`.
This fixes a nil pointer crash in the actuator.
```release-note
This fixes an actuator crash in environments that do not have any `cluster` objects set, e.g. OpenShift.
```

Read clusterName from machine if cluster is nil

---

pkg/cloud/openstack/machine/actuator.go

This PR allows the nodelink-controller to match the machine with the node.
```release-note
NONE
```

add machine status

---

pkg/cloud/openstack/machine/instancestatus.go

The `actuator.Update` function was exiting immediately, because
`oc.instanceStatus` was always returning an error.
`instanceStatus` was calling `util.GetMachineIfExists` from
`cluster-api` which looks up `Machine` objects under the
`Group:"cluster.k8s.io"` and `Version:"v1alpha1"` rather than the
`machine.openshift.io` and `v1beta1`. This always resulted in a
`NoKindMatchError`.
Instead, we've added a local `GetMachineIfExists` function which does
use the right `Machine` version, making `Update` work correctly.
Fixes https://github.com/openshift/installer/issues/1467
**Special notes for your …

machine/actuator: Fix Update instance status

---

pkg/cloud/openstack/machine/instancestatus.go

We are still hitting panics in the actuator even after
83d7a2879f68241f227c835b00ae0e38fb6f7d76
It looks like we now hit them in the updateInstaceStatus function.
This function is using the same util.GetMachineIfExists function
that was causing kernel panics in the instanceStatus function.
Instead we can use the function we created to fix the previous
panics.

Use local GetMachineIfExists function instead of cluster-api

---

OWNERS_ALIASES

Removed trown and flaper87.
Added Fedosin and mandre.
Fixes #
```release-note
```

Refresh cluster-api-openstack-maintainers

---

pkg/cloud/openstack/machine/actuator.go

If the instance was accidentally destroyed for a machine we shouldn't try to create a new one with the old name, because because the CSR for it will not be approved automatically.
Currently we just return an error and the broken machine should be deleted manually.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1746369

Bug 1746369: return an error if the instance has been destroyed

---

pkg/cloud/openstack/machine/actuator.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1747245

Bug 1747245: return an error if the cluster name label is incorrect

---

OWNERS_ALIASES

Add adduarte to openstack approvers

---

OWNERS_ALIASES

I'm no longer working on OpenShift and the relevant repos directly.

Remove Tomas Sedovic from OWNERS_ALIASES

---

pkg/cloud/openstack/clients/machineservice.go
pkg/cloud/openstack/machine/actuator.go

This commits adds validation that there is one and only one image with the given name.

Bug 1805025: validate that image exists before creating a machine

---

.gitignore
vendor/github.com/googleapis/gnostic/openapiv2/openapi-2.0.json

One file in a vendored folder matched an exclude rule in `.gitignore`.

Fix vendoring

---

OWNERS_ALIASES

owners: Add mdbooth

---

Makefile
hack/verify-vendor.sh

Add a helper script to check that vendoring is not corrupted.

hack: Add verify-vendor.sh

---

Dockerfile

Bug 1933667: Update ose-openstack-machine-controllers builder & base images to be consistent with ART

---

Dockerfile
pkg/apis/openstackproviderconfig/v1alpha1/types.go
pkg/cloud/openstack/clients/machineservice.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/doc.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/requests.go
vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsecurity/results.go
vendor/modules.txt

Contains a number of bugfixes and features needed to fully support the OpenShift SR-IOV Operator.
Please see each commit for more details.
Fixes:  [OSASINFRA-2364](https://issues.redhat.com/browse/OSASINFRA-2364)

Sriov Addons

---

hack/e2e.sh

This directory can be cleaned up at the end of the exection.

hack/e2e: cleanup tmp dir

---

openshift/Makefile

This is step 1 of 3 in the dance necessary to add e2e tests. Next up, the job definition itself (in `openshift/release`).
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>
n/a
n/a
**TODOs**:
n/a
/hold

Add stub e2e target

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-25639: Add Snyk file to exclude vendor directory on scan

---

.snyk

Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!

OCPBUGS-24296: Add Snyk file to exclude vendor directory on scan

---

Makefile
api/v1alpha5/zz_generated.conversion.go
api/v1alpha6/openstackcluster_conversion.go
api/v1alpha6/zz_generated.conversion.go
api/v1alpha7/openstackcluster_conversion.go
api/v1alpha7/zz_generated.conversion.go
api/v1beta1/types.go
config/manager/manager.yaml
main.go
openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
openshift/vendor/sigs.k8s.io/cluster-api-provider-openstack/api/v1beta1/types.go
pkg/cloud/services/networking/port.go
pkg/webhooks/fuzz_test.go
pkg/webhooks/openstackcluster_webhook.go
test/e2e/suites/apivalidations/openstackcluster_test.go

NO-JIRA: Bump to latest CAPO v0.10

---

.snyk
hack/tools/vendor/sigs.k8s.io/cluster-api-provider-openstack/.snyk

Clarify why we skip a file in snyk.

CARRY: add comment to .snyk about Glance
