openshift/cluster-api-provider-openstack

Dockerfile.installer.ci
Adds a Dockerfile that can be used in the e2e openshift installer job to test CAPO.
=> Add CI Dockerfile for e2e test

Makefile, README.md, config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml, config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderstatus.yaml, config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml, config/manager/deployment.yaml, config/rbac/rbac_role.yaml, docs/config.md, docs/trouble_shooting.md, overlays-config/coreos/manager/deployment.yaml, overlays-config/generic/manager/deployment.yaml, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/apis/openstackproviderconfig/v1alpha1/zz_generated.deepcopy.go, pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/secgroupservice.go, pkg/cloud/openstack/cluster/actuator.go, pkg/cloud/openstack/machine/actuator.go, pkg/cloud/openstack/options/options.go
**What this PR does / why we need it**: Pulls down changes from upstream that benefit us
This pull request is a little. For now, we are going to merge upstream patches that are useful, or would prevent merge conflicts in the future.
=> Integrating useful changes from upstream

Makefile, config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderspec.yaml, config/crds/openstackproviderconfig_v1alpha1_openstackclusterproviderstatus.yaml, config/crds/openstackproviderconfig_v1alpha1_openstackproviderspec.yaml, config/rbac/rbac_role.yaml, pkg/apis/openstackproviderconfig/v1alpha1/doc.go, pkg/apis/openstackproviderconfig/v1alpha1/register.go
Rename `openstackproviderconfig.k8s.io` to `openstackproviderconfig.openshift.io`.
All openshift machine types are required to live under .openshift.io group.
The same holds for provider configs/specs which are shipped with openshift by default.
Fixes #
```release-note
```
=> Rename schema group to openshift io

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/machine/actuator.go
This commit sets additional machine annotations/labels to get pretty machine output.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1724204
=> Bug 1724204: Set additional machine annotations/labels

OWNERS, OWNERS_ALIASES, SECURITY_CONTACTS
Only allow OpenShift Shiftstack team members to be owners
#57
=> limit owners to shiftstack team

pkg/cloud/openstack/machine/actuator.go
Now if CAPO cannot create an image it ignores the error and continue operating as the creation was successful.
This patch returns the error if something wrong happens.
=> Bug 1745939: Return error if image creation fails

pkg/cloud/openstack/machine/actuator.go
Now if CAPO cannot create an instance it ignores the error and continue operating as the deletion was successful.
This patch returns the error if something wrong happens.
=> Bug 1746015: Return error if instance deletion fails

pkg/cloud/openstack/machine/instancestatus.go
Now we use k8s API to create a machine that later will be deleted, but since this API is not registered in OpenShift we have an empty struct as a result.
Later the actuator will parse the providerSpec of the machine and fail because it cannot be found.
This patch changes the API correct "machine.openshift.io"
=> Bug 1746015: provide correct API to machine serialization

Gopkg.lock, config/rbac/rbac_role.yaml, pkg/cloud/openstack/machine/actuator.go
**What this PR does / why we need it**: Enables Event recording so that the interface is comparable to CAPA does things
**Which issue(s) this PR fixes**: https://bugzilla.redhat.com/show_bug.cgi?id=1746019
=> bug 1746019: Add event recording for machines

pkg/cloud/openstack/clients/machineservice.go
The Machine service, upon machine creation, looks in OpenStack for
networks and subnets matching the Machine Networks specificiation.
Before this change, if no matching network was found, the Instance spec
was sent to OpenStack with an empty Network segment.
With this change, the Machine service returns an error to the caller if
no matching networks are found in Openstack.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1746021
=> Bug 1746021: Abort Instance if no valid network

Dockerfile, Dockerfile.rhel7
Minimal golang version for k8s 1.16 is 1.12 so we have to upgrade our images.
=> Bump golang from 1.10 to 1.12

Makefile
In k8s 1.16 "--domain" option was removed from controller-gen, so now we have to explicitly specify paths to our apis and the output directory.
=> Change manifests generation

pkg/cloud/openstack/machine/actuator.go
Prior to this change, the feature-flag disabled all updates. With this
change, the feature-flag only disables master updates, as originally
intended.
=> Bug 1751471: Apply update to workers selectively

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
**What this PR does / why we need it**: Adds ability to trust CA bundle to CAPO
=> Bug 1769879: allow CA Cert bundles to be trusted

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
Corrects Self Signed Certs support to pull from centralized location in the cluster, the openshift-config:cloud-provider-config configmap.
=> Bug 1769879: SSC refractor

pkg/cloud/openstack/clients/machineservice.go
This makes it easier to debug in case CAPO can't read the CA cert from
the `openshift-config/cloud-provider-config` configmap.
=> Bug 1795035: Give reason for not using cloud provider CA cert

pkg/cloud/openstack/clients/machineservice.go
This is a backport of #79 and #80
=> [release-4.3] Bug 1796822: Support deployment on OpenStack with self-signed certificate

pkg/cloud/openstack/machine/actuator.go
With this change, the new machine is created first. The desired outcome
is that in case the new machine specification is not valid, its
creation fails and the old one does not get deleted.
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1751471
/cc Fedosin mandre
=> Bug 1751471: Machine update: create before delete

Gopkg.lock, pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/schedulerhints/requests.go
With this change, it is possible to pass an OpenStack Server Group[1] in
the machine configuration, so that the machine will be assigned to it.
Prerequisite for OSASINFRA-1300 (soft-anti-affinity)
[1]: https://docs.openstack.org/python-openstackclient/latest/cli/command-objects/server-group.html
=> Add ServerGroupID to OpenstackProviderSpec

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
This commit allows to set a flag to NetworkParameter that disables allowed address pairs creation for all network ports.
=> Bug 1815029: Allow to create network ports without allowed address pairs

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/utils.go, pkg/cloud/openstack/machine/actuator.go
This patch allows to set primary ip address for the machine based on
the primary network tag `<clusterInfraID>-primaryClusterNetwork`. In the case of multiple attached networks this tag should allow CAPO to define which IP address to set as the primary one for machines.
Now CAPO can't do this, because Neutron returns the list of networks in alphabetical order.
=> Bug 1824426: Allow to define primary ip address for machines

pkg/cloud/openstack/clients/machineservice.go
If the instance is not Active, then when we try to delete it, Neutron may fail to delete its ports, and therefore we can't delete the instance after that.
This patch accepts the fact that ports may not be removed, and continues deleting the instance anyway.
=> Bug 1804596: Continue deleting the instance if its ports haven't been destroyed

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/microversions.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/results.go, vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/extensions/servergroups/urls.go, vendor/modules.txt
A server group with the corresponding name and "soft-anti-affinity"
policy will be created if it does not exist already.
=> Bug 1823487: Add ServerGroupName to OpenstackProviderSpec

cmd/manager/main.go
Introduces leader-election option for machine controllers, allowing to eliminate edge cases when multiple controllers could be running. Allows integration with MAO PR: https://github.com/openshift/machine-api-operator/pull/571
Fixes #
```release-note
```
=> Add Leader election flags for machine controller

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/utils.go, pkg/cloud/openstack/machine/actuator.go
This patch allows to set primary ip address for the machine based on
the primary network tag "<clusterInfraID>-primaryClusterNetwork".
In the case of multiple attached networks this tag should allow CAPO to
define which IP address to set as the primary one for machines.
Now CAPO can't do this, because Neutron returns the list of networks
in alphabetical order.
Cherry-picked from https://github.com/openshift/cluster-api-provider-openstack/pull/88
=> [release-4.4] Bug 1839012: Allow to define primary ip address for machines

cmd/manager/main.go
This change backports the leader election mechanism to the 4.5 branch by cherry-picking the following commits:
2fe5ec95a17ebc1807706df7cc0437a5fb380309
9c64f488ba4200759de53e28f9e4acd0708569d2
**Which issue(s) this PR fixes**
Bugzilla 1864352
=> Bug 1864352: Update leader election for release 4.5

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/machine/actuator.go
Instead of using tags on the subnet, we want the user to be able to have control over the primary subnet in a more standardized way. We are moving the functionality to the provider spec. In most use cases, this will be set automatically by the installer, however, this gives the user the ability to manually override it based on their use case.
/cc @mandre
=> make primary subnet a programatic part of provider spec

Dockerfile
We don't need openssh in the image so there is no reason to keep it.
=> Drop openssh from the image

pkg/cloud/openstack/machine/actuator.go
To change machine status to Failed we need to return `InvalidConfigurationMachineError`.
=> Bug 1805025: return correct error if machine validation fails

Dockerfile.rhel
Updating ose-openstack-machine-controllers builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-openstack-machine-controllers.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Bug 1909723: Updating ose-openstack-machine-controllers builder & base images to be consistent with ART

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/machine/actuator.go
When we boot a machine from volume, we don't need to fetch the image id.
=> Bug 1913736: do not fetch image id when booting from volume

pkg/cloud/openstack/clients/machineservice.go, vendor/github.com/gophercloud/utils/openstack/compute/v2/availabilityzones/utils.go, vendor/modules.txt
Now that we have updated vendoring for gophercloud/utils, we can use the
latest utils to list available AZs and stop maintaining our own
function.
=> [cleanup] use gophercloud/utils to list available AZs

OWNERS
Bug reported against CAPO should be filled under `Cloud Compute ->
OpenStack Provider`.
=> Update BZ component

Dockerfile.rhel
openssh is not expected to be useful in the production image.
=> images: Remove openssh from the RHEL variant

go.mod, pkg/cloud/openstack/machineset/controller.go, vendor/modules.txt
Use the new fmt.Errorf "%w" verb instead.
/hold Can wait until 4.8 master is open.
=> Remove pkg/errors dependency

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/machineservice_test.go
Gives users the ability to tag the ports CAPO creates based on the network or subnet they are attached to. Some Usage patterns in the ProviderSpec are as follows:
```yaml
...
tags:
- tag1
Networks:
- uuid: ****-****-****-net1
portTags:
- tag2
subnets:
- uuid: ****-****-****-snet1
portTags: 
- tag3
- uuid: ****-****-****-snet2
portTags: 
- tag4
```
tag1: all resources created by CAPO
tag2: all ports attached to network net1 created by CAPO
tag3: all ports attached to subnet snet1 created by CAPO
tag4: all ports attached to subnet snet2 created by CAPO
Fixes: [OSASINFRA-2348](https://issues.redhat.com/browse/OSASINFRA-2348)
=> Tag Ports Created By CAPO Based on Network or Subnet Attached

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/doc.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/requests.go, vendor/github.com/gophercloud/gophercloud/openstack/networking/v2/extensions/portsbinding/results.go, vendor/modules.txt
Adding the vnicType to the network definition allows for the user to select the type of openstack network port that will be createdc. 
https://issues.redhat.com/browse/OSASINFRA-2335
=> Adds vnictype to port creation

pkg/cloud/openstack/clients/machineservice.go
The server list api defines the name parameter to be a regular
expression:
https://docs.openstack.org/api-ref/compute/?expanded=list-servers-detail#list-servers
This meant that the usage of it in InstanceService.GetInstanceList was a
substring lookup rather than the intended lookup by name.
Fixes: rhbz1747270
```release-note
NONE
```
=> Bug 1747270: InstanceService.GetInstanceList should not do substring search on name

pkg/apis/openstackproviderconfig/v1alpha1/types.go
The json argument is `networkId` when the standard naming scheme for
fields ending in ID dictates that it should be named `networkID`.
=> Ports NetworkID json typo

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
There were a number of issues in the way we allowed users to create ports/interfaces for nodes through the machine API. This patch looks to clean them up to prevent race conditions or OpenStack errors that could cause a deployment to fail due to logical errors in cluster-api-provider-openstack.
=> Bug 1948546: Port create bugs

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
The allowed Address pairs were using the gohpercloud ports.allowed
address pairs struct. This prevents us from being in control of the api,
and may lead to unexpected updates. This also causes the names in the
api to be underscored instead of camel case, which is inconsistent.
=> Bug 1952179: Port Allowed Address Pairs UI

pkg/cloud/openstack/clients/machineservice.go
Rather than require users to use the networks and subnets to define a
networking interface for an instance, users should be able to just
define them using the ports api if they choose to. This removes
validation checking that a user entered at least one network and subnet,
and insteand checks that a user entered at least one network, subnet, or
port.
Fixes Bug 1948546:
The correct way to configure the OpenStack provider spec in a machineset with interfaces on networks with port security disabled is now as follows in the example below. This is because it is impossible to attach networks with port security enabled when a security group is set on the instance. It will fail with: `Network requires port_security_enabled and subnet associated in order to apply security groups.`
```yaml …
```
=> Bug 1948546: Allow all networking interfaces to be defined as ports

pkg/cloud/openstack/clients/machineservice.go
The bugzilla in question is rooted on attempting to create
ports with the same name.
This patch uses the subnet and netids as name suffixes for ports.
Also limits the length of the port name to no more than 255 characters, which is in line with what the current neutron db schema can tolerate. 
https://issues.redhat.com/browse/OCPBUGSM-28624
=> Bug 1955969: - Makes port names unique.

pkg/cloud/openstack/clients/machineservice.go
InstanceCreate is a method that creates a server. If the server is set
to boot from volume, and an image ID is passed, the method creates the
root volume prior to creating the server. The root volume is set to be
destroyed when the associated server is destroyed.
However, if the server fails to create (for example, because of quota
issues), the volume is never associated to a server and the automatic
deletion is never triggered. At every round of retry, a new volume will
be created, possibly until volume quota is reached (or server creation
is successful). This results in a leakage of unused volumes.
With this patch, a newly created root volume is explicitly deleted as
soon as the server creation call fails.
Note that this patch leaves unmodified the lifespan of a volume
associated to a …
=> Bug 1943378: Eliminate instanceCreate volume leak

pkg/cloud/openstack/clients/machineservice.go, pkg/cloud/openstack/clients/utils.go
Prior to this change, if machine-controller gets reprovisioned in the
middle of running InstanceCreate, stale volumes might be left on the
cluster.
With this change, before creating a new root volume for an instance,
InstanceCreate deletes any volumes with the same name.
=> Bug 1983612: Make InstanceCreate idempotent

pkg/cloud/openstack/clients/machineservice.go
With this change, the volume cleanup is triggered by any early failure
of InstanceCreate. That is to say: if InstanceCreate creates a volume,
that volume will be deleted if any of the next steps fail and cause the
server never to be created.
=> Bug 1943378: Fix InstanceCreate volume cleanup

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
Extend trunk configuration to port level in machineset
With the introduction of new technologies, like SR-IOV,
it is required that the user have the ability to
configured trunked and not-trunked ports for the same machines
using spec.ports.trunk.
- Extended trunk support needed check to cover spec.port and spec.network
- Makes ports inherit trunk setting from spec.Trunk if not specified.
- Refactored trunking to its own function. Trunk name matches port name
- Added trunking to spec.ports
[OSASINFRA-2504](https://issues.redhat.com/browse/OSASINFRA-2504)
=> Bug 1964540: Extend trunk configuration to port level in machineset

pkg/cloud/openstack/clients/machineservice.go
InstanceCreate is a method that creates a server. If the server is set
to boot from volume, and an image ID is passed, the method creates the
root volume prior to creating the server. The root volume is set to be
destroyed when the associated server is destroyed.
However, if the server fails to create (for example, because of quota
issues), the volume is never associated to a server and the automatic
deletion is never triggered. At every round of retry, a new volume will
be created, possibly until volume quota is reached (or server creation
is successful). This results in a leakage of unused volumes.
With this change, a newly created root volume is explicitly deleted in
the event of an early failure of InstanceCreate. That is to say: if
InstanceCreate creates a volume, that volume will be …
=> Bug 1985015: Eliminate instanceCreate volume leak

pkg/cloud/openstack/clients/utils.go
Enables machine-controller to use proxy from environment variables injected into the container.
=> Bug 1986540: Adds Proxy to provider client http transport

pkg/apis/openstackproviderconfig/v1alpha1/types.go, pkg/cloud/openstack/clients/machineservice.go
Upstream: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/964
Configuring port profiles can be useful to enable an application
running on the specified host to pass and receive VIF port-specific
information to the plugin.
One of the use-cases here is when configuring ports in OVS Hardware
offload, where we need to use the profile:
{"capabilities": ["switchdev"]}
Thanks to this patch, we'll now able to do it when creating the
machines and their ports.
[OSASINFRA-2434](https://issues.redhat.com/browse/OSASINFRA-2434)
=> Bug 1996155: UPSTREAM: 964: getOrCreatePort: add support to configure port Profile

pkg/cloud/openstack/clients/machineservice.go
There is a known issue with Cisco ACI [1] that causes the query to
return subnets that don't belong to the specified network. We can
workaround it and ensure the subnets really belong to the network.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2027305
=> Bug 2033862: Ensure subnets belong to the queried network

Makefile, hack/e2e.sh
This commit adds e2e test to Makefile.  This test
will clone cluster-api-actuator-pkg and run tests
from that clone.
Copied from GCP's provider [1].
[1] https://github.com/openshift/machine-api-provider-gcp/commit/492fd64f713f51a89a317d75649bf5181e6292ba
=> Add target to run e2e tests

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
See the [Prometheus advisory](https://github.com/prometheus/client_golang/security/advisories/GHSA-cg3q-j54f-5p7p)
This patch upgrades `github.com/prometheus/client_golang` to v1.11.1,
where the vulnerability has been fixed.
This commit is the result of running:
```
go get github.com/prometheus/client_golang \
&& go mod tidy && go mod vendor
```
**Notes for the reviewer**:
One handy way to check that the version of `client_go` used for compiling contains the security patch, is to check that the vendored code contains a `InstrumentRoundTripperCounter` method [accepting a variadic `options` argument](https://github.com/prometheus/client_golang/compare/v1.11.0...v1.11.1#diff-7871a83741d29b5f29e3c47d1c284f948c258a0c6fc18895f0c2d4204cc46054R63).
For …
=> Bug 2067870: Address CVE-2022-21698

pkg/cloud/openstack/clients/machineservice.go
With this change, the port and trunk cleanups are triggered by any
early failure of InstanceCreate.
When InstanceCreate creates ports and if it creates trunks, these
resources will be deleted if any of the next steps fail and cause the
server never to be created.
Note: the trunk will be deleted first, then the ports.
=> Bug 2073398: Fix InstanceCreate port & trunk cleanup

pkg/cloud/openstack/clients/machineservice.go
Before this change, setting `noAllowedAddressPairs` on a machine-pool network could have effect on a different network.
Given this example configuration:
```yaml
networks:
- filter: {}
noAllowedAddressPairs: false
subnets:
- filter: {}
uuid: primary-subnet-uuid
- filter: {}
noAllowedAddressPairs: true
subnets:
- filter: {}
uuid: other-subnet-uuid
primarySubnet: primary-subnet-uuid
```
The filter of the second network the array is empty. This means that its `subnet` filter has to be applied without restrictions as to which network it's sitting on. However, the absence of a network filter also meant that the setting `noAllowedAddressPairs` would apply to all networks.
With this change, `noAllowedAddressPairs` is applied on a subnet basis, meaning that only ports created in the subnets …
=> OCPBUGS-1765: Apply noAllowedAddressPairs on intended subnets only

pkg/cloud/openstack/clients/machineservice.go
Commit 855a22c09317457ecfd08544afac6948cfdfe462 introduced a bug that caused network definitions without subnets (the one you would get when setting `additionalNetworkIDs` in your `install-config.yaml`) caused the noAllowedAddressPairs property to be skipped while creating the port.
This may in turn caused machine-api to fail creating the port because it does not have the permission to create a port with allowed_address_pair, which is often the case when using provider networks.
=> OCPBUGS-2508: Ensure network defs without subnet follow noAllowedAddressPairs

pkg/cloud/openstack/clients/machineservice.go
Commit 855a22c09317457ecfd08544afac6948cfdfe462 introduced a bug that caused network definitions without subnets (the one you would get when setting `additionalNetworkIDs` in your `install-config.yaml`) caused the noAllowedAddressPairs property to be skipped while creating the port.
This may in turn caused machine-api to fail creating the port because it does not have the permission to create a port with allowed_address_pair, which is often the case when using provider networks.
=> OCPBUGS-2628: Ensure network defs without subnet follow noAllowedAddressPairs

pkg/cloud/services/compute/instance_types.go, pkg/cloud/services/compute/instance_types_test.go
Dual-stack clusters require that the Machine's status contains the IPv6 address. This commit removed the check that would skip the addition of IPv6 to the Machines. Also, it ensures the IPv4 addresses of each Network remains being the first ones listed in the Machines given there are operations that rely on the first address of each network.
Cherry-pick of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/commit/5926f47ecc7307d617e0efd1148a52969bbbca0d
=> Add support to IPv6 in Machine's status

Dockerfile.rhel
This is required for it to be included in the release payload. CAPO is actually deployed by cluster-capi-operator, but is not directly referenced by cluster-capi-operator. cluster-capi-operator instead consumes a ConfigMap deployed by CAPO. CAPO must be included in the release payload in order for cluster-capi-operator to be able to consume this ConfigMap.
/hold
=> CARRY: Mark CAPO as second level operator

OWNERS, OWNERS_ALIASES
We are now using DOWNSTREAM_OWNERS instead. We can restore OWNERS and OWNERS_ALIASES to upstream to avoid future merge conflicts.
TODO:
/hold
=> CARRY: Restore OWNERS to upstream

config/certmanager/certificate.yaml, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_openstackclusters.yaml, config/crd/patches/cainjection_in_openstackclustertemplates.yaml, config/crd/patches/cainjection_in_openstackmachines.yaml, config/crd/patches/cainjection_in_openstackmachinetemplates.yaml, config/default/kustomization.yaml, config/default/manager_webhook_patch.yaml, config/webhook/cainjection_patch.yaml, config/webhook/kustomization.yaml
(cherry picked from commit 661c0ff3dee81915c6d82b005e2efaa04826febb)
/hold
=> UPSTREAM 1726: Replace kustomize vars with replacements

openshift/.golangci.yml, openshift/Makefile, openshift/cmd/manager.go, openshift/pkg/infraclustercontroller/openstackcluster.go, openshift/pkg/scheme/scheme.go
Also fix lint issues hightlighted by these tests.
=> openshift: Add make verify and test

openshift/kustomize/cluster-capi-configmap/kustomization.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
Incorrect label prevents deployment by cluster-capi-operator.
/hold
=> 🐛 openshift: Fix label of cluster-capi infrastructure CM

.snyk
This previously caused the job to fail with:
✗ [High] the referenced anchor is not defined: */vendor/**
ID: 62e8960c-5e98-4900-b60c-b67ea2a03767
Path: .snyk, line 7
Info: the referenced anchor is not defined: */vendor/**
=> Fix syntax in .skyk

openshift/kustomize/components/common/kustomization.yaml, openshift/kustomize/credentials-request/credentials-request.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_00_credentials-request.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
Builds on #293; you may want to review that one first.
openshift/machine-api-operator@9c20871740 (openshift/machine-api-operator#1174) added this capability to the machine-API analog of this manifest.  And openshift/cluster-capi-operator@e305541274 (openshift/cluster-capi-operator#143) annotated some cluster-API CredentialsRequests used for other  providers.  This commit catches cluster-API OpenStack up with those other changes.
There is a risk that tech-preview clusters updating into this change will have the CloudCredential capability implicitly enabled.  But because tech-preview clusters with the CloudCredential capability disabled were not installable, there should be no exposed clusters attempting those updates.
=> OCPBUGS-26027: openshift/manifests: CloudCredential capability for CredentialsRequest

.snyk
In addition to vendor directories, we can ignore things that do not end up in the product.
=> OCPBUGS-25859: CARRY: Add Snyk security scan config

openshift/kustomize/infracluster-controller/controller.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
This addresses only the infra-cluster-controller. For the primary CAPO controller I would like to fix this upstream and cherry-pick here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2070
=> OCPBUGS-33170: openshift: Set FallbackToLogsOnError on infra-cluster controller

.snyk, hack/tools/vendor/sigs.k8s.io/cluster-api-provider-openstack/.snyk
We allow to check SHA1 and md5 for Glance images, we can ignore these
security concerns.
=> snyk: ignore md5 & SHA1 warnings for ORC images

Makefile
Both cherry-pick conflict because orc wasn't a thing yet.
- CARRY: Makefile: add `merge-bot` target
- CARRY: Makefile: add `generate-openshift`
=> OCPBUGS-44959: Makefile changes for merge-bot

.ci-operator.yaml, Dockerfile.rhel, hack/tools/vendor/sigs.k8s.io/cluster-api-provider-openstack/.ci-operator.yaml, hack/tools/vendor/sigs.k8s.io/cluster-api-provider-openstack/Dockerfile.rhel
Supersedes https://github.com/openshift/cluster-api-provider-openstack/pull/344
=> OCPBUGS-45387: Updating openstack-cluster-api-controllers-container image to be consistent with ART for 4.19

openshift/kustomize/components/tech-preview/kustomization.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_00_credentials-request.yaml, openshift/manifests/0000_30_cluster-api-provider-openstack_04_infrastructure-components.yaml
As was done for the other providers previously [1]. This was achieved by
modifying 'kustomization.yaml' and running:
make -C openshift generate
[1] https://github.com/openshift/cluster-capi-operator/pull/238
=> OSASINFRA-3722: Deploy manifests for CustomNoUpgrade feature set also

openshift/pkg/infraclustercontroller/openstackcluster.go
Failing to set this breaks from CAPI v1.9 onwards.
/hold
=> OCPCLOUD-2857: Set infrastructureRef.Namespace in Cluster object
